### ISSUE TITLE
Facing issues while using Yolo object detection model

### ISSUE THREAD

**Issue by avidLearnerInProgress** [avidLearnerInProgress/optimal-image-resizing#14]
While integrating I realised that Yolo reszies the images to its convenient size for prediction of objects.
Is it possible to use Yolo with the same image size?

The bounding boxes which will be predicted in object detection after resizing the image will vary and it will become difficult to integrate this model in the project.

Need help.!

**Comment by luenix** [comment]
Looks like you're going to need to grok [https://github.com/pjreddie/darknet/blob/master/src/normalization_layer.c](https://github.com/pjreddie/darknet/blob/master/src/normalization_layer.c)

**Comment by luenix** [comment]
Also [https://github.com/pjreddie/darknet/blob/master/src/image.c](https://github.com/pjreddie/darknet/blob/master/src/image.c) resize_max/min.
